import type { Metadata } from "next"
import "@/style/globals.css"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased dark h-dvh
          bg-[url('/images/background.jpg')] bg-cover bg-no-repeat"
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
